name: Release orangepi 5 noble desktop

on:
  push:
    tags:
      - "*"
  workflow_dispatch:


permissions:
  contents: write

run-name: Release orangepi 5 plus

jobs:
  prepare_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: true
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    runs-on: ubuntu-latest
    needs: [prepare_release]
    name: Build image
    strategy:
      matrix:
        board:
          - orangepi-5-plus
        addon:
          - ""
          - holomotion
          - mongodb
          - trainging
    steps:  
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: false
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: sudo ./build.sh ${{ matrix.board }} ${{ matrix.addon }}

      - name: Upload to release
        if: needs.prepare_release.outputs.release_id != ''
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
          file: images/ubuntu-*-preinstalled-*-arm64-${{ matrix.board }}*${{ matrix.addon }}*
          draft: false
          overwrite: true

      - name: Clean cache
        run: sync && sudo rm -rf ./images/ubuntu-*-preinstalled-*-arm64-${{ matrix.board }}*${{ matrix.addon }}* && sync
